services:
  warehouse-backend:
    image: openjdk:25-ea-4-jdk-oraclelinux9
    container_name: warehouse-backend
    ports:
      - "8082:8080"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      SPRING_RABBITMQ_HOST: host.docker.internal
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    volumes:
      - ./target/warehouse-0.0.1-SNAPSHOT.jar:/app/warehouse-0.0.1-SNAPSHOT.jar
      - ./logs:/logs
    command: [ "java", "-jar", "/app/warehouse-0.0.1-SNAPSHOT.jar" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  warehouse_db:
#    image: postgres:latest
#    container_name: warehouse_db
#    environment:
#      POSTGRES_DB: warehouseDB
#      POSTGRES_USER: sa
#      POSTGRES_PASSWORD: sa
#    ports:
#      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6390:6379"
    expose:
      - "9121"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8100:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
