spring:
  application:
    name: warehouse

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console




  datasource:
    url: jdbc:h2:mem:warehouseDB;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 1.5

  websocket:
    allowed-origins: "*"

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000

  web:
    pageable:
      default-page-size: 10
      max-page-size: 100

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

appconfig:
  cache:
    enabled: true

server:
  servlet:
    context-path: /api