spring:
  application:
    name: warehouse


  datasource:
    url: jdbc:postgresql://localhost:5432/warehouseDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 1.5

  websocket:
    allowed-origins: "*"

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000

  web:
    pageable:
      default-page-size: 10
      max-page-size: 100

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

